%--------------------------------------------------------------------------
% Hannah Lee
% AMATH 383 Spring 2020
% University of Washington
% model_comp takes the figures generated by hh_model and hh_reduced and
% superimposes the plots in order to compare the behavior.
%--------------------------------------------------------------------------

clear all; close all; clc;

% comparing the membrane potential of the original HH model and the reduced
% model, with an externally applied current of 10 mV

original = open('hh_membrane.fig');
reduced = open('reduced_membrane.fig');
ax1 = get(original, 'Children');
ax2 = get(reduced, 'Children');
ax2p = get(ax2(1), 'Children');
copyobj(ax2p, ax1(1));

